Document: yaknewtab
Title: Debian yaknewtab Manual
Author: <insert document author here>
Abstract: This manual describes what yaknewtab is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yaknewtab/yaknewtab.sgml.gz

Format: postscript
Files: /usr/share/doc/yaknewtab/yaknewtab.ps.gz

Format: text
Files: /usr/share/doc/yaknewtab/yaknewtab.text.gz

Format: HTML
Index: /usr/share/doc/yaknewtab/html/index.html
Files: /usr/share/doc/yaknewtab/html/*.html
